name: MCManHunt
version: ${project.version}
main: io.github.thesummergrinch.mcmanhunt.MCManHunt
api-version: 1.16
load: STARTUP
authors: [ TheSummerGrinch ]
description: ManHunt-plugin to be used for the ManHunt-minigame, as seen in Dream and GeorgeNotFound's videos.
website: https://github.com/TheSummerGrinch/MCManHunt
commands:
  joinhunters:
    description: Places the user in the Hunter-team.
    usage: /joinhunters
    permission: mcmanhunt.player.team
  joinrunners:
    description: Places the user in the Runner-team.
    usage: /joinrunners
    permission: mcmanhunt.player.team
  leaveteam:
    description: Removes the user from their team.
    usage: /leaveteam
    permission: mcmanhunt.player.team
  addhunter:
    description: Forcibly adds a player to the Hunter-team.
    usage: /addhunter [playername]
    permission: mcmanhunt.player.admin
  addrunner:
    description: Forcibly adds a player to the Runner-team.
    usage: /addrunner [playername]
    permission: mcmanhunt.player.admin
  listrunners:
    description: Lists the names of all the players on the Runner-team.
    usage: /listrunners
    permission: mcmanhunt.player.info
  listhunters:
    description: Lists the names of all the players on the Hunter-team.
    usage: /listhunters
    permission: mcmanhunt.player.info
  setmaxrunners:
    description: Sets the maximum amount of players allowed on the Runner-team.
    usage: /setmaxrunners [Integer]
    permission: mcmanhunt.config
  setmaxhunters:
    description: Sets the maximum amount of players allowed on the Hunter-team.
    usage: /setmaxhunters [Integer]
    permission: mcmanhunt.config
  pausegame:
    description: Pauses the game.
    usage: /pausegame
    permission: mcmanhunt.gameflow
  resumegame:
    description: Resumes a paused game.
    usage: /resumegame
    permission: mcmanhunt.gameflow
  startgame:
    description: Starts a game.
    usage: /startgame
    permission: mcmanhunt.gameflow
  stopgame:
    description: Stops an ongoing game.
    usage: /stopgame
    permission: mcmanhunt.gameflow
permissions:
  mcmanhunt.config:
    description: Gives access to configuration-options.
    default: op
  mcmanhunt.gameflow:
    description: Gives access to Gameflow-commands.
    default: op
  mcmanhunt.player.admin:
    description: Gives access to Admin-commands.
    default: op
  mcmanhunt.player.info:
    description: Gives access to basic information.
    default: true
  mcmanhunt.player.team:
    description: Gives access to basic team-commands.
    default: true

