name: MCManHunt
version: ${project.version}
main: io.github.thesummergrinch.mcmanhunt.MCManHunt
api-version: 1.16
commands:
  initializegame:
    description: Initializes a game.
    usage: /intializegame [gamename]
    permission: mcmanhunt.game.op
    aliases: [ initgame, mhinit ]
  joingame:
    description: The user joins the specified game.
    usage: /joingame [gamename]
    permission: mcmanhunt.game.join
  startgame:
    description: Starts the specified game.
    usage: /startgame [gamename]
    permission: mcmanhunt.game.op
  listrole:
    description: Lists the specified role, or list both teams if the /listteams label is used.
    usage: /listrole [runners|hunters] [GameName]
    permission: mcmanhunt.game.info
    aliases: [ listrunners, listhunters, listteams ]
  listgames:
    description: Lists all initialized games.
    usage: /listgames
    permission: mcmanhunt.game.info
  jointeam:
    description: The user joins the specified team.
    usage: /jointeam [runners|hunters]
    permission: mcmanhunt.game.join
    aliases: [ joinhunters, joinrunners ]
  pausegame:
    description: The specified game is paused, or the game the user is currently in is paused.
    usage: /pausegame [Optional Gamename]
    permission: mcmanhunt.game.op
  resumegame:
    description: The specified game is resumed, or the game the user is currently in is resumed.
    usage: /resumegame [Optional Gamename]
    permission: mcmanhunt.game.op
  stopgame:
    description: The specified game is stopped, or the game the user is currently in is stopped.
    usage: /stopgame [Optional Gamename]
    permission: mcmanhunt.game.op
  destroyuniverse:
    description: Marks the specified Universe for destruction.
    usage: /destroyuniverse [Universename]
    permission: mcmanhunt.game.op
  setdestroyuniverseonstop:
    description: Marks the specified Universe to be either destroyed or preserved when the game stops.
    usage: /setdestroyuniverseonstop [Universename] [true|false]
    permission: mcmanhunt.game.op
    aliases: [ sdos ]
  manhuntversion:
    description: Echos the version of the plugin.
    usage: /manhuntversion
    permission: mcmanhunt.plugin.info
    aliases: [ mhv ]
  manhuntrule:
    description: Allows the user to set a ManHunt-gamerule.
    usage: /mhrule [GameName] [Rulename] [Value]
    permission: mcmanhunt.game.op
    aliases: [ mhr ]
permissions:
  mcmanhunt.game.op:
    description: Allows the user access to op-commands related to the MCManHunt-plugin.
    default: op
  mcmanhunt.game.join:
    description: Allows the user to access the /joingame-command and /jointeam-command.
    default: true
  mcmanhunt.game.info:
    description: Allows the user access to various informative commands.
    default: true
  mcmanhunt.plugin.info:
    description: Allows access to informative commands.
    default: op
